version: '3.8'

services:
  backend:
    build:
      context: ./backend
    image: ${DOCKER_HUB_USERNAME:-local}/ci-cd-demo:backend
    ports:
      - "3001:3001"
    env_file:
      - backend/.env

  frontend:
    build:
      context: ./frontend
    image: ${DOCKER_HUB_USERNAME:-local}/ci-cd-demo:frontend
    ports:
      - "3000:3000"
    env_file:
      - frontend/.env
    depends_on:
      - backend 